// Arduino Mega Pins
//
//    connect to USB           0; //      PE0 ( RXD0/PCINT8 )
//    connect to USB           1; //      PE1 ( TXD0 )
const int RTC_SQW            = 2; //      PE4 ( OC3B/INT4 )
const int IR_RECEIVE         = 3; //      PE5 ( OC3C/INT5 )
//                             4; //      PG5 ( OC0B )
//                             5; //      PE3 ( OC3A/AIN1 )
const int TRIG              =  6; //      PH3 ( OC4A ) // for Hero 3+ Black only
const int HSYNC             =  7; //      PH4 ( OC4B )
//      connect to D47 <----   8; //      PH5 ( OC4C )
const int SECONDARY_RESET   =  9; //      PH6 ( OC2B )
const int MODE_SWITCH       = 10; //      PB4 ( OC2A/PCINT4 )
const int SETUP_SWITCH      = 11; //      PB5 ( OC1A/PCINT5 )
const int SHUTTER_SWITCH    = 12; //      PB6 ( OC1B/PCINT6 )
//                            13; //      PB7 ( OC0A/OC1C/PCINT7 )
//                            14; //      PJ1 ( TXD3/PCINT10 )
//                            15; //      PJ0 ( RXD3/PCINT9 )
//    broadcast to MewPro     16; //      PH1 ( TXD2 )
//                            17; //      PH0 ( RXD2 )
//                            18; //      PD3 ( TXD1/INT3 )
//                            19; //      PD2 ( RXDI/INT2 )
//    connect to RTC          20; //      PD1 ( SDA/INT1 )
//    connect to RTC          21; //      PD0 ( SCL/INT0 )
//                            22; //      PA0 ( AD0 )
//                            23; //      PA1 ( AD1 )
//                            24; //      PA2 ( AD2 )
//                            25; //      PA3 ( AD3 )
//                            26; //      PA4 ( AD4 )
//                            27; //      PA5 ( AD5 )
//                            28; //      PA6 ( AD6 )
//                            29; //      PA7 ( AD7 )
//                            30; //      PC7 ( A15 )
//                            31; //      PC6 ( A14 )
//                            32; //      PC5 ( A13 )
//                            33; //      PC4 ( A12 )
//                            34; //      PC3 ( A11 )
//                            35; //      PC2 ( A10 )
//                            36; //      PC1 ( A9 )
//                            37; //      PC0 ( A8 )
//                            38; //      PD7 ( T0 )
//                            39; //      PG2 ( ALE )
//                            40; //      PG1 ( RD )
//                            41; //      PG0 ( WR )
//                            42; //      PL7
//                            43; //      PL6
//                            44; //      PL5 ( OC5C )
const int VSYNC             = 45; //      PL4 ( OC5B )
//                            46; //      PL3 ( OC5A )
//  connect from D8 ------>   47; //      PL2 ( T5 )
//                            48; //      PL1 ( ICP5 )
//                            49; //      PL0 ( ICP4 )
//                            50; //      PB3 ( MISO/PCINT3 )
//                            51; //      PB2 ( MOSI/PCINT2 )
//                            52; //      PB1 ( SCK/PCINT1 )
//                            53; //      PB0 ( SS/PCINT0 )
const int LCD_RS            = 54; //  A0; PF0 ( ADC0 )
const int LCD_ENABLE        = 55; //  A1; PF1 ( ADC1 )
const int LCD_DATA4         = 56; //  A2; PF2 ( ADC2 )
const int LCD_DATA5         = 57; //  A3; PF3 ( ADC3 )
const int LCD_DATA6         = 58; //  A4; PF4 ( ADC4/TMK )
const int LCD_DATA7         = 59; //  A5; PF5 ( ADC5/TMS )
//                            60; //  A6; PF6 ( ADC6 )
//                            61; //  A7; PF7 ( ADC7 )
//                            62; //  A8; PK0 ( ADC8/PCINT16 )
//                            63; //  A9; PK1 ( ADC9/PCINT17 )
//                            64; // A10; PK2 ( ADC10/PCINT18 )
//                            65; // A11; PK3 ( ADC11/PCINT19 )
//                            66; // A12; PK4 ( ADC12/PCINT20 )
//                            67; // A13; PK5 ( ADC13/PCINT21 )
//                            68; // A14; PK6 ( ADC14/PCINT22 )
//                            69; // A15; PK7 ( ADC15/PCINT23 )
/* Regrettably, the following pins are NOT broken out in Arduino Mega board.
   Didn't Mega's designer aware of importance of Tn pins etc?
   We are very lucky T5 if no Tn pins else is broken out and usable as D47 by accident.
   (Seeeduino Mega has these pins cleverly broken out, but no Arduino pin names used by Arduino IDE.) */
//                            N/C; // PH2 ( XCK2 )
//                            N/C; // PH7 ( T4 )
//                            N/C; // PJ2 ( XCK3/PCINT11 )
//                            N/C; // PJ3 ( PCINT12 )
//                            N/C; // PJ4 ( PCINT13 )
//                            N/C; // PJ5 ( PCINT14 )
//                            N/C; // PJ6 ( PCINT15 )
//                            N/C; // PJ7
//                            N/C; // PD4 ( ICP1 )
//                            N/C; // PD5 ( XCK1 )
//                            N/C; // PD6 ( T1 )
//                            N/C; // PG4 ( TOSC1 )
//                            N/C; // PG3 ( TOSC2 )
//                            N/C; // PE7 ( CLKO/ICP3/INT7 )
//                            N/C; // PE6 ( T3/INT6 )
//                            N/C; // PE2 ( XCK0/AIN0 )

